services:
  portfolio:
    env_file:
      - path: .env # default
        required: true
      - path: .env.override # optional override
        required: false
    container_name: portfolio
    networks:
      - portfolio
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
      args:
        - TZ=${PORTFOLIO_TZ}
        - UID=${UID}
        - GID=${GID}
    environment:
      DEBUG: ${DEBUG}
      GO_ENV: ${GO_ENV}
      TZ: ${PORTFOLIO_TZ}
    volumes:
      - .:/portfolio
      - ui_node_modules:/portfolio/ui/node_modules
      - ui_pnpm_store:/portfolio/ui/.pnpm-store
      - go_build:/home/app/.cache/go-build
    ports:
      - "5173:5173"
      - "3000:3000"
networks:
  portfolio:

volumes:
  ui_node_modules:
  ui_pnpm_store:
  go_build: